package mocks

import mock "github.com/stretchr/testify/mock"
import types "gitlab.bertha.cloud/partitio/Nextcloud-Partitio/gonextcloud/types"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Apps provides a mock function with given fields:
func (_m *Client) Apps() types.Apps {
	return new(Apps)
}

// AppsConfig provides a mock function with given fields:
func (_m *Client) AppsConfig() types.AppsConfig {
	return new(AppsConfig)
}

// GroupFolders provides a mock function with given fields:
func (_m *Client) GroupFolders() types.GroupFolders {
	return new(GroupFolders)
}

// Groups provides a mock function with given fields:
func (_m *Client) Groups() types.Groups {
	return new(Groups)
}

// Notifications provides a mock function with given fields:
func (_m *Client) Notifications() types.Notifications {
	return new(Notifications)
}

// Shares provides a mock function with given fields:
func (_m *Client) Shares() types.Shares {
	return new(Shares)
}

// Users provides a mock function with given fields:
func (_m *Client) Users() types.Users {
	return new(Users)
}
